apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy01
  name: deploy01
  namespace: workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy01
  template:
    metadata:
      labels:
        app: deploy01
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
